<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Tidy T-Test in R With Cohen&#39;s D - Matthew E. Vanaman</title>
  <meta name="renderer" content="webkit" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>

<meta http-equiv="Cache-Control" content="no-transform" />
<meta http-equiv="Cache-Control" content="no-siteapp" />

<meta name="theme-color" content="#f8f5ec" />
<meta name="msapplication-navbutton-color" content="#f8f5ec">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="#f8f5ec">


<meta name="author" content="Matthew E. Vanaman" /><meta name="description" content="Where’s My Effect Size? Walk-Through of my.t()  Default T-Test in R T-Test Using my.t() Output Formatting  Full Function References   The independent-samples \(t\)-test is one of the most commonly used statistical tests and is taught in most introductory statistics courses. In broad strokes, the independent-samples $t$-test is used to compare the means of some continuous variable between two qualitatively different groups. Associated with this mean difference is a \(p\)-value." /><meta name="keywords" content="Hugo, theme, even" />






<meta name="generator" content="Hugo 0.80.0 with theme even" />


<link rel="canonical" href="/post/2021-01-31-tidy-t-test-with-cohen-s-d/" />
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">



<link href="/sass/main.min.2e81bbed97b8b282c1aeb57488cc71c8d8c8ec559f3931531bd396bf31e0d4dd.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css" integrity="sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY=" crossorigin="anonymous">


<meta property="og:title" content="Tidy T-Test in R With Cohen&#39;s D" />
<meta property="og:description" content="Where’s My Effect Size? Walk-Through of my.t()  Default T-Test in R T-Test Using my.t() Output Formatting  Full Function References   The independent-samples \(t\)-test is one of the most commonly used statistical tests and is taught in most introductory statistics courses. In broad strokes, the independent-samples $t$-test is used to compare the means of some continuous variable between two qualitatively different groups. Associated with this mean difference is a \(p\)-value." />
<meta property="og:type" content="article" />
<meta property="og:url" content="/post/2021-01-31-tidy-t-test-with-cohen-s-d/" />
<meta property="article:published_time" content="2021-01-31T00:00:00+00:00" />
<meta property="article:modified_time" content="2021-01-31T18:55:54-05:00" />
<meta itemprop="name" content="Tidy T-Test in R With Cohen&#39;s D">
<meta itemprop="description" content="Where’s My Effect Size? Walk-Through of my.t()  Default T-Test in R T-Test Using my.t() Output Formatting  Full Function References   The independent-samples \(t\)-test is one of the most commonly used statistical tests and is taught in most introductory statistics courses. In broad strokes, the independent-samples $t$-test is used to compare the means of some continuous variable between two qualitatively different groups. Associated with this mean difference is a \(p\)-value.">
<meta itemprop="datePublished" content="2021-01-31T00:00:00+00:00" />
<meta itemprop="dateModified" content="2021-01-31T18:55:54-05:00" />
<meta itemprop="wordCount" content="1715">



<meta itemprop="keywords" content="r,tidy,t-test,effect-size,cohens-d," />
<meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="Tidy T-Test in R With Cohen&#39;s D"/>
<meta name="twitter:description" content="Where’s My Effect Size? Walk-Through of my.t()  Default T-Test in R T-Test Using my.t() Output Formatting  Full Function References   The independent-samples \(t\)-test is one of the most commonly used statistical tests and is taught in most introductory statistics courses. In broad strokes, the independent-samples $t$-test is used to compare the means of some continuous variable between two qualitatively different groups. Associated with this mean difference is a \(p\)-value."/>

<!--[if lte IE 9]>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/classlist/1.1.20170427/classList.min.js"></script>
<![endif]-->

<!--[if lt IE 9]>
  <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
<![endif]-->

</head>
<body>
  <div id="mobile-navbar" class="mobile-navbar">
  <div class="mobile-header-logo">
    <a href="/" class="logo">Matthew E. Vanaman</a>
  </div>
  <div class="mobile-navbar-icon">
    <span></span>
    <span></span>
    <span></span>
  </div>
</div>
<nav id="mobile-menu" class="mobile-menu slideout-menu">
  <ul class="mobile-menu-list">
    <a href="/">
        <li class="mobile-menu-item">Home</li>
      </a><a href="/post/">
        <li class="mobile-menu-item">Blog</li>
      </a><a href="/research/">
        <li class="mobile-menu-item">Research</li>
      </a><a href="/about/">
        <li class="mobile-menu-item">About</li>
      </a><a href="/research/">
        <li class="mobile-menu-item">Research</li>
      </a>
  </ul>

  


</nav>

  <div class="container" id="mobile-panel">
    <header id="header" class="header">
        <div class="logo-wrapper">
  <a href="/" class="logo">Matthew E. Vanaman</a>
</div>





<nav class="site-navbar">
  <ul id="menu" class="menu">
    <li class="menu-item">
        <a class="menu-item-link" href="/">Home</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/post/">Blog</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/research/">Research</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/about/">About</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/research/">Research</a>
      </li>
  </ul>
</nav>

    </header>

    <main id="main" class="main">
      <div class="content-wrapper">
        <div id="content" class="content">
          <article class="post">
    
    <header class="post-header">
      <h1 class="post-title">Tidy T-Test in R With Cohen&#39;s D</h1>

      <div class="post-meta">
        <span class="post-time"> 2021-01-31 </span>
        
        
      </div>
    </header>

    <div class="post-toc" id="post-toc">
  <h2 class="post-toc-title">Contents</h2>
  <div class="post-toc-content">
    
  </div>
</div>
    <div class="post-content">
      
<script src="/post/2021-01-31-tidy-t-test-with-cohen-s-d/index.en_files/header-attrs/header-attrs.js"></script>
<script src="/post/2021-01-31-tidy-t-test-with-cohen-s-d/index.en_files/kePrint/kePrint.js"></script>
<link href="/post/2021-01-31-tidy-t-test-with-cohen-s-d/index.en_files/lightable/lightable.css" rel="stylesheet" />

<div id="TOC">
<ul>
<li><a href="#wheres-my-effect-size">Where’s My Effect Size?</a></li>
<li><a href="#walk-through-of-my.t">Walk-Through of <code>my.t()</code></a>
<ul>
<li><a href="#default-t-test-in-r">Default T-Test in <code>R</code></a></li>
<li><a href="#t-test-using-my.t">T-Test Using <code>my.t()</code></a></li>
<li><a href="#output-formatting">Output Formatting</a></li>
</ul></li>
<li><a href="#Function">Full Function</a></li>
<li><a href="#references">References</a></li>
</ul>
</div>

<p>The independent-samples <span class="math inline">\(t\)</span>-test is one of the most commonly used statistical tests and is taught in most introductory statistics courses. In broad strokes, the independent-samples $t$-test is used to compare the means of some continuous variable between two qualitatively different groups. Associated with this mean difference is a <span class="math inline">\(p\)</span>-value. Although there’s <a href="https://en.wikipedia.org/wiki/Sampling_distribution" target="_blank">more to the story</a>, for our purposes we can define the <span class="math inline">\(p\)</span>-value as the probability of observing a difference between the means this large or larger, just due to chance, if there were in reality no difference between the groups. Although arbitrary, researchers will adopt (for most applications) a cutoff <span class="math inline">\(p\)</span>-value of .05, a value referred to as alpha. If the $p$-value falls below alpha, we can conclude that the difference between the means is large enough to warrant further scrutiny.</p>
<div id="wheres-my-effect-size" class="section level1">
<h1>Where’s My Effect Size?</h1>
<p>Effect sizes help contextualize the results of statistical tests, which consensus is more often beginning to recognize as the least interesting part of statistical output <span class="citation">(<a href="#ref-sullivan2012using" role="doc-biblioref">Sullivan &amp; Feinn, 2012</a>)</span>. Indeed, researchers have been pressured to report measures of effect size alongside descriptive and inferential statistics in their published work for about two decades now <span class="citation">(<a href="#ref-coe2002effect" role="doc-biblioref">Coe, 2002</a>)</span>. As most introductory statistics courses will teach, Cohen’s $d$ follows some rules of thumb that help give a sense of how impressive the magnitude of the mean difference is <span class="citation">(<a href="#ref-cohen2013statistical" role="doc-biblioref">Cohen, 2013</a>)</span>:</p>
<ul>
<li><span class="math inline">\(\le 0.2\)</span> is “small”</li>
<li><span class="math inline">\(0.5\)</span> is “medium”</li>
<li><span class="math inline">\(\ge 0.8\)</span> is “large”</li>
</ul>
<p>One would be forgiven for expecting to see this reported alongside the default output of standard statistical software. You almost always need it. I so far have been unable to find a function that provides this, and have become annoyed enough to finally create my own wrapper function that uses <code>R</code>’s built-in <code>t.test()</code> function and the <code>cohen.d()</code> function from the <code>psych</code> package. The output, unlike that of the default <code>t.test()</code> function, is in a <a href="https://vita.had.co.nz/papers/tidy-data.pdf" target="_blank">tidy format</a>.</p>
<p>Feel free to skip to the <a href="#Function">full function</a> at the bottom; if you want a preview, keep reading.</p>
</div>
<div id="walk-through-of-my.t" class="section level1">
<h1>Walk-Through of <code>my.t()</code></h1>
<div id="default-t-test-in-r" class="section level2">
<h2>Default T-Test in <code>R</code></h2>
<p>The <code>t.test()</code> function, which is built in to base-<code>R</code> along with other mainstream tests, has messy output. It also doesn’t provide the mean difference, the standard error of the difference, or Cohen’s <span class="math inline">\(d\)</span>. As an example of its use, I’ll conduct a <span class="math inline">\(t\)</span>-test to see whether automatic or manual transmissions are associated with greater miles per gallon. This data can be found in the <code>mtcars</code> dataset (from the <code>datasets</code> package, also available in base-<code>R</code>):</p>
<pre class="r"><code># t.test(DV ~ IV, data)
# am = automatic or manual
# mpg = miles per gallon
t.test(mpg ~ am, mtcars)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  mpg by am
## t = -3.7671, df = 18.332, p-value = 0.001374
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -11.280194  -3.209684
## sample estimates:
## mean in group 0 mean in group 1 
##        17.14737        24.39231</code></pre>
<p>In this dataset, vehicles with automatic transmissions are coded as 0, and manuals as 1. The dependent variable is miles per gallon. The mean miles per gallon for vehicles with automatic transmissions (17.15) is quite a bit lower than for vehicles with manual transmissions (24.39). This difference is statistically significant, <span class="math inline">\(p = .001\)</span> (that’s less than an alpha of .05), meaning the means are different enough that we might interested in investigating a bit further. At this point, you’d usually calculate Cohen’s <span class="math inline">\(d\)</span>.</p>
</div>
<div id="t-test-using-my.t" class="section level2">
<h2>T-Test Using <code>my.t()</code></h2>
<pre class="r"><code>my.t(mtcars, IV = am, DV = mpg)</code></pre>
<table class="table" style>
<caption>
<span id="tab:table1">Table 1: </span>T-Test With <code>my.t</code> (IV = Transmission and DV = Miles Per Gallon)
</caption>
<thead>
<tr>
<th style="text-align:right;">
0.mean
</th>
<th style="text-align:right;">
1.mean
</th>
<th style="text-align:right;">
0.sd
</th>
<th style="text-align:right;">
1.sd
</th>
<th style="text-align:right;">
mean.difference
</th>
<th style="text-align:right;">
std.err
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
<th style="text-align:right;">
t
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:right;">
p.value
</th>
<th style="text-align:left;">
cohens.d
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
17.15
</td>
<td style="text-align:right;">
24.39
</td>
<td style="text-align:right;">
3.83
</td>
<td style="text-align:right;">
6.17
</td>
<td style="text-align:right;">
-7.24
</td>
<td style="text-align:right;">
1.92
</td>
<td style="text-align:right;">
-11.28
</td>
<td style="text-align:right;">
-3.21
</td>
<td style="text-align:right;">
-3.77
</td>
<td style="text-align:right;">
18.33
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:left;">
1.53
</td>
</tr>
</tbody>
</table>
<p>The output in Table <a href="#tab:table1">1</a> above provides all of the relevant statistics, clearly labeled, with Cohen’s <span class="math inline">\(d\)</span> included, and in a tidy format that can easily be exported to a .csv file, copied-and-pasted into Word, or printed within an R Markdown as a table as I have done here (using <code>knitr::kable()</code>).</p>
</div>
<div id="output-formatting" class="section level2">
<h2>Output Formatting</h2>
<p>Currently the output is in wide format, meaning that each statistic is its own column with the values for those statistics contained in the table row. If you prefer a different format, I have also added the <code>long =</code> argument that can optionally display output in long format, with all of the values in a single column with the statistic indicated by the row:</p>
<pre class="r"><code>my.t(mtcars, IV = am, DV = mpg, long = TRUE)</code></pre>
<table class="table" style>
<caption>
<span id="tab:table2">Table 2: </span>T-Test With <code>my.t</code> in Long Format (IV = Transmission and DV = Miles Per Gallon)
</caption>
<thead>
<tr>
<th style="text-align:left;">
Statistic
</th>
<th style="text-align:right;">
Value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
0.mean
</td>
<td style="text-align:right;">
17.15
</td>
</tr>
<tr>
<td style="text-align:left;">
1.mean
</td>
<td style="text-align:right;">
24.39
</td>
</tr>
<tr>
<td style="text-align:left;">
0.sd
</td>
<td style="text-align:right;">
3.83
</td>
</tr>
<tr>
<td style="text-align:left;">
1.sd
</td>
<td style="text-align:right;">
6.17
</td>
</tr>
<tr>
<td style="text-align:left;">
mean.difference
</td>
<td style="text-align:right;">
-7.24
</td>
</tr>
<tr>
<td style="text-align:left;">
std.err
</td>
<td style="text-align:right;">
1.92
</td>
</tr>
<tr>
<td style="text-align:left;">
conf.low
</td>
<td style="text-align:right;">
-11.28
</td>
</tr>
<tr>
<td style="text-align:left;">
conf.high
</td>
<td style="text-align:right;">
-3.21
</td>
</tr>
<tr>
<td style="text-align:left;">
t
</td>
<td style="text-align:right;">
-3.77
</td>
</tr>
<tr>
<td style="text-align:left;">
df
</td>
<td style="text-align:right;">
18.33
</td>
</tr>
<tr>
<td style="text-align:left;">
p.value
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;">
cohens.d
</td>
<td style="text-align:right;">
1.53
</td>
</tr>
</tbody>
</table>
<p>Personally, I like the long format, because usually I am running more than one <span class="math inline">\(t\)</span>-test. For example, say that in my car-shopping, miles per gallon was one of just several criteria I were using to decide what kind of car to buy. In addition to miles per gallon, I might compare automatic vs manual transmissions in their level of <em>displacement</em>, which roughly describes “how fast a vehicle gets up and goes” (my <a href="https://matthewevanaman.netlify.app/img/dad.jpeg" target="_blank">dad</a> built engines for 40 years, so I hope he will forgive me if this description is less than accurate). Displacement is measured in cubic inches. Below is a table with the output of both tests side-by-side:</p>
<pre class="r"><code># conduct the tests
mpg.test &lt;- my.t(mtcars, IV = am, DV = mpg, long = TRUE)
disp.test &lt;- my.t(mtcars, IV = am, DV = disp, long = TRUE)
# relabel the columns with the name of the DV
mpg.test &lt;- mpg.test %&gt;% rename(MPG = Value)
disp.test &lt;- disp.test %&gt;% rename(&quot;Disp.&quot; = Value)
# combine into one dataframe
my.results &lt;- left_join(mpg.test, disp.test, by = &quot;Statistic&quot;)
# print the table
my.results</code></pre>
<table class="table" style>
<caption>
<span id="tab:table3">Table 3: </span>Comparing Group Differences in MPG and Displacement
</caption>
<thead>
<tr>
<th style="text-align:left;">
Statistic
</th>
<th style="text-align:right;">
MPG
</th>
<th style="text-align:right;">
Disp.
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
0.mean
</td>
<td style="text-align:right;">
17.15
</td>
<td style="text-align:right;">
290.38
</td>
</tr>
<tr>
<td style="text-align:left;">
1.mean
</td>
<td style="text-align:right;">
24.39
</td>
<td style="text-align:right;">
143.53
</td>
</tr>
<tr>
<td style="text-align:left;">
0.sd
</td>
<td style="text-align:right;">
3.83
</td>
<td style="text-align:right;">
110.17
</td>
</tr>
<tr>
<td style="text-align:left;">
1.sd
</td>
<td style="text-align:right;">
6.17
</td>
<td style="text-align:right;">
87.20
</td>
</tr>
<tr>
<td style="text-align:left;">
mean.difference
</td>
<td style="text-align:right;">
-7.24
</td>
<td style="text-align:right;">
146.85
</td>
</tr>
<tr>
<td style="text-align:left;">
std.err
</td>
<td style="text-align:right;">
1.92
</td>
<td style="text-align:right;">
34.98
</td>
</tr>
<tr>
<td style="text-align:left;">
conf.low
</td>
<td style="text-align:right;">
-11.28
</td>
<td style="text-align:right;">
75.33
</td>
</tr>
<tr>
<td style="text-align:left;">
conf.high
</td>
<td style="text-align:right;">
-3.21
</td>
<td style="text-align:right;">
218.37
</td>
</tr>
<tr>
<td style="text-align:left;">
t
</td>
<td style="text-align:right;">
-3.77
</td>
<td style="text-align:right;">
4.20
</td>
</tr>
<tr>
<td style="text-align:left;">
df
</td>
<td style="text-align:right;">
18.33
</td>
<td style="text-align:right;">
29.26
</td>
</tr>
<tr>
<td style="text-align:left;">
p.value
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;">
cohens.d
</td>
<td style="text-align:right;">
1.53
</td>
<td style="text-align:right;">
-1.49
</td>
</tr>
</tbody>
</table>
<p>As shown in Table <a href="#tab:table3">3</a>, the mean difference in displacement between automatics and manuals is 146.85, meaning that automatic transmissions are associated with an extra 146.85 cubic inches of displacement on average. So while you might lose ~7 miles to the gallon by going with an automatic transmission, you can also expect to gain ~147 cubic inches of displacement.</p>
<p>OK, but what the heck does that mean? Is that an impressive number? It’s hard to tell for those who don’t spend time dealing with vehicle displacement. At least with miles per gallon, I can readily discern about how much money I would save if my vehicle got an extra 7 miles to the gallon. Displacement is a black box to me - I can’t tell if that mean difference in displacement is meaningful or not, especially not compared to how meaningful the difference in miles per gallon was.</p>
<p>In Table <a href="#tab:table3">3</a>, the Cohen’s <span class="math inline">\(d\)</span> statistics for miles per gallon and displacement are conveniently side-by-side. Both are very large effect sizes - quite a bit larger than 0.8, the rule of thumb for a large. Although the sign for displacement is negative (indicating that manual transmissions are associated with lower displacement than automatics), the absolute value is very close to that of miles per gallon. It seems like whatever gas I’d save with a manual transmission, I’d lose an equally-meaningful amount of displacement per cubic inch. That is, with Cohen’s <span class="math inline">\(d\)</span>, I can see that the <em>magnitude</em> of the differences between between automatic and manual transmissions (effect sizes of 1.53 and -1.49, respectively) are pretty similar, even though the mean differences themselves (7.24 miles per gallon and -146.85 cubic inches of displacement, respectively) are not comparable numbers.</p>
<p>Of course, miles per gallon and displacement might be too conceptually different to be compared meaningfully without added context. These tests would be most helpful if you also knew what adding 146.85 of displacement per cubic inch would feel like in terms of pushing your back against the seat as you accelerate in your new car. Maybe you would need, say, twice as much displacement (or 293.7 cubic inches) in order for a gain in displacement to be noticeable. But in the absence of better information, it’s nice to know for the sake of car shopping that the <em>magnitude of the difference between the groups</em> is basically the same for miles per gallon and displacement.</p>
</div>
</div>
<div id="Function" class="section level1">
<h1>Full Function</h1>
<p>Copy-and-paste this function to use it in your own <code>R</code> projects. You will be prompted to install the <code>tidyverse</code> and <code>psych</code> packages if you do not already have them.</p>
<pre class="r"><code>my.t &lt;-
    function(data, IV, DV, long = FALSE, ...) {
      require(tidyverse)
      require(psych)
      IV.1 &lt;- enquo(IV)
      DV.1 &lt;- enquo(DV)
      means &lt;- suppressMessages(
        data %&gt;%
        group_by(!!IV.1) %&gt;%
        summarise(mean = mean(!!DV.1, na.rm = TRUE)) %&gt;%
          pivot_wider(names_from = !!IV.1, values_from =  &quot;mean&quot;)
        )
      names(means) &lt;- paste(names(means), &quot;mean&quot;, sep = &quot;.&quot;)
      SDs &lt;- suppressMessages(
        data %&gt;%
          group_by(!!IV.1) %&gt;%
          summarise(sd = sd(!!DV.1, na.rm = TRUE)) %&gt;%
          pivot_wider(names_from = !!IV.1, values_from =  &quot;sd&quot;)
      )
      names(SDs) &lt;- paste(names(SDs), &quot;sd&quot;, sep = &quot;.&quot;)

      IV.2 &lt;- rlang::sym(rlang::as_label(rlang::enquo(IV)))
      DV.2 &lt;- rlang::sym(rlang::as_label(rlang::enquo(DV)))
      form &lt;- expr(!! DV.2 ~ !! IV.2)
      t.tests &lt;- t.test(eval(form), data, var.equal = FALSE)
      stats &lt;- t.tests %&gt;% broom::glance(x)
      std.err &lt;- t.tests$stderr
      Ds &lt;-
        cohen.d(x = data %&gt;% select(!!DV.1, !!IV.1),
                group = deparse(substitute(IV)))$cohen.d %&gt;%
        as.data.frame %&gt;%
        select(effect) %&gt;%
        round(2) %&gt;%
        format(nsmall = 2)
      cols &lt;- c(&quot;conf.low&quot;, &quot;conf.high&quot;, &quot;statistic&quot;, &quot;parameter&quot;, &quot;p.value&quot;)
      means.table &lt;-
        cbind(means, SDs, stats[, &quot;estimate&quot;], std.err, stats[, cols], Ds)
      means.table &lt;- means.table %&gt;%
        rename(mean.difference = estimate, cohens.d = effect, t = statistic, df = parameter)
      rownames(means.table) &lt;- NULL
      if (long == TRUE) {
        means.table.long &lt;-
          means.table %&gt;% 
          t %&gt;% 
          data.frame(&quot;Value&quot; = .) %&gt;% 
          rownames_to_column(&quot;Statistic&quot;) %&gt;% 
          mutate(Value = as.numeric(as.character(Value))) %&gt;% 
          mutate(Value = round(Value, 2))
        return(means.table.long)
      } else{
        return(means.table)
      }
    }</code></pre>
</div>
<div id="references" class="section level1 unnumbered">
<h1>References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" line-spacing="2">
<div id="ref-coe2002effect" class="csl-entry">
Coe, R. (2002). <em>It’s the effect size, stupid: What effect size is and why it is important</em>. <a href="http://www.leeds.ac.uk/educol/documents/00002182.htm">Full Text</a>
</div>
<div id="ref-cohen2013statistical" class="csl-entry">
Cohen, J. (2013). <em>Statistical power analysis for the behavioral sciences</em>. Academic press. <a href="https://books.google.com/books?hl=en&amp;lr=&amp;id=rEe0BQAAQBAJ&amp;oi=fnd&amp;pg=PP1&amp;dq=Statistical+power+analysis+for+the+behavioral+sciences.&amp;ots=swUSKrRTu8&amp;sig=RqINXdX_uJjD_mB6UerWX-JBgVg#v=onepage&amp;q=Statistical%20power%20analysis%20for%20the%20behavioral%20sciences.&amp;f=false">Full Text</a>
</div>
<div id="ref-sullivan2012using" class="csl-entry">
Sullivan, G. M., &amp; Feinn, R. (2012). Using effect size—or why the p value is not enough. <em>Journal of Graduate Medical Education</em>, <em>4</em>(3), 279. <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3444174/">Full Text</a>
</div>
</div>
</div>

    </div>

    
<footer class="post-footer">
      <div class="post-tags">
          <a href="/tags/r/">r</a>
          <a href="/tags/tidy/">tidy</a>
          <a href="/tags/t-test/">t-test</a>
          <a href="/tags/effect-size/">effect-size</a>
          <a href="/tags/cohens-d/">cohens-d</a>
          </div>
      <nav class="post-nav">
        
        
      </nav>
    </footer>
  </article>
        </div>
        

  

  

      </div>
    </main>

    <footer id="footer" class="footer">
      <div class="social-links">
      <a href="mailto:your@email.com" class="iconfont icon-email" title="email"></a>
      <a href="https://www.linkedin.com/in/mvanaman/" class="iconfont icon-linkedin" title="linkedin"></a>
  <a href="/index.xml" type="application/rss+xml" class="iconfont icon-rss" title="rss"></a>
</div>

<div class="copyright">
  <span class="power-by">
    Powered by <a class="hexo-link" href="https://gohugo.io">Hugo</a>
  </span>
  <span class="division">|</span>
  <span class="theme-info">
    Theme - 
    <a class="theme-link" href="https://github.com/olOwOlo/hugo-theme-even">Even</a>
  </span>

  

  <span class="copyright-year">
    &copy; 
    2021<span class="heart"><i class="iconfont icon-heart"></i></span><span>olOwOlo</span>
  </span>
</div>

    </footer>

    <div class="back-to-top" id="back-to-top">
      <i class="iconfont icon-up"></i>
    </div>
  </div>
  
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js" integrity="sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY=" crossorigin="anonymous"></script>



<script type="text/javascript" src="/js/main.min.c12618f9a600c40bd024996677e951e64d3487006775aeb22e200c990006c5c7.js"></script>
  <script type="text/javascript">
    window.MathJax = {
      tex: {
        inlineMath: [['$','$'], ['\\(','\\)']],
        tags: 'ams',
        }
    };
  </script>
  <script async src="https://cdn.jsdelivr.net/npm/mathjax@3.0.5/es5/tex-mml-chtml.js" integrity="sha256-HGLuEfFcsUJGhvB8cQ8nr0gai9EucOOaIxFw7qxmd+w=" crossorigin="anonymous"></script>








</body>
</html>
