---
title: Tidy T-Test in R With Cohen's D
author: Matthew E. Vanaman
date: '2021-01-31'
slug: []
categories: []
tags:
  - r
  - tidy
  - t-test
  - effect-size
  - cohens-d
lastmod: '2021-01-31T18:55:54-05:00'
keywords: []
description: ''
comment: yes
output: 
  blogdown::html_page:
    toc: true
    fig_cap: yes
postMetaInFooter: no
hiddenFromHomePage: no
contentCopyright: no
reward: no
mathjax: yes
mathjaxEnableSingleDollar: yes
mathjaxEnableAutoNumber: yes
hideHeaderAndFooter: no
flowchartDiagrams:
  enable: no
  options: ''
sequenceDiagrams:
  enable: no
  options: ''
bibliography: "/Users/home/Documents/Research and Writing/Misc/MyRefs/MyRefs.bib"
link-citations: true
csl: "/Users/home/Documents/Research and Writing/Misc/MyRefs/apa-web.csl"
---

<script src="{{< blogdown/postref >}}index.en_files/header-attrs/header-attrs.js"></script>
<script src="{{< blogdown/postref >}}index.en_files/kePrint/kePrint.js"></script>
<link href="{{< blogdown/postref >}}index.en_files/lightable/lightable.css" rel="stylesheet" />

<div id="TOC">
<ul>
<li><a href="#wheres-my-effect-size">Where’s My Effect Size?</a></li>
<li><a href="#my-solution">My Solution</a>
<ul>
<li><a href="#formatting-option-and-an-illustration">Formatting Option, and an Illustration</a></li>
</ul></li>
<li><a href="#full-function">Full Function</a></li>
<li><a href="#references">References</a></li>
</ul>
</div>

<!--id="post-toc"-->
<p>The independent-samples <span class="math inline">\(t\)</span>-test is one of the most commonly used statistical tests and is taught in most introductory statistics courses. In broad strokes, the independent-samples $t$-test is used when the independent variable in a study is binary - that is, consists of two qualitatively different groups - and the dependent variable is continuous (interval or ratio). The mean of the dependent variable is calculated for each group, compared, and a decision is made about whether the difference between the means is meaningful (that is, worth paying attention to). Associated with this mean difference is a <span class="math inline">\(p\)</span>-value. Although there’s <a href="https://en.wikipedia.org/wiki/Sampling_distribution" target="_blank">more to the story</a>, for our purposes we can define the <span class="math inline">\(p\)</span>-value as the probability of observing a difference between the means this large or larger, just due to chance, if there were in reality no difference between the groups. Although arbitrary, researchers will adopt (for most applications) a cutoff <span class="math inline">\(p\)</span>-value of .05, a value referred to as alpha. If the $p$-value falls below alpha, we can conclude that the difference between the means is large enough to warrant further scrutiny.</p>
<div id="wheres-my-effect-size" class="section level1">
<h1>Where’s My Effect Size?</h1>
<p>In the aforementioned introductory statistics courses, students also learn about effect sizes that help put the results of statistical tests into context. In the case of the <span class="math inline">\(t\)</span>-test, Cohen’s <span class="math inline">\(d\)</span> measure of effect size helps the researcher get a sense of how impressive the mean difference between groups is on a standardized metric. Standardized, in this case, just means that the metric is universal: no matter what the original metric for the dependent variable, the $d$ statistic always falls within a certain range, and always follows a certain interpretation. This means that if you ran two different tests on two different dependent variables, the interpretations of their resulting $d$ statistics would be comparable in terms of your sense of how large the mean differences were. Although still a bit arbitrary, $d$ follows some rules of thumb <span class="citation">(<a href="#ref-cohen2013statistical" role="doc-biblioref">Cohen, 2013</a>)</span>:</p>
<ul>
<li><span class="math inline">\(\le 0.2\)</span> = is “small”</li>
<li><span class="math inline">\(0.5\)</span> is “medium”</li>
<li><span class="math inline">\(\ge 0.8\)</span> is “large”</li>
</ul>
<p>Given how useful this is, one might expect to see it among the default output from standard statistical software. It’s odd, then, that software in general does not automatically report Cohen’s <span class="math inline">\(d\)</span> alongside the results of independent-samples <span class="math inline">\(t\)</span>-tests. This, despite the fact that researchers have been pressured to report measures of effect size alongside descriptive and inferential statistics in their published work for about two decades now <span class="citation">(<a href="#ref-coe2002effect" role="doc-biblioref">Coe, 2002</a>)</span>.</p>
<p>The <code>t.test()</code> function, which is built in to base-<code>R</code> along with other mainstream tests, is unfortunately no different. As an example of its use, I’ll conduct a <span class="math inline">\(t\)</span>-test to see whether automatic or manual transmissions are associated with greater miles per gallon. This data can be found in the <code>mtcars</code> dataset (from the <code>datasets</code> package, also available in base-<code>R</code>):</p>
<pre class="r"><code>t.test(mpg ~ am, mtcars)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  mpg by am
## t = -3.7671, df = 18.332, p-value = 0.001374
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -11.280194  -3.209684
## sample estimates:
## mean in group 0 mean in group 1 
##        17.14737        24.39231</code></pre>
<p>In this dataset, vehicles with automatic transmissions are coded as 0, and manuals as 1. The dependent variable is miles per gallon. Looking at the output above, we see the mean miles per gallon for vehicles with automatic transmissions (17.15) is quite a bit lower than for vehicles with manual transmissions (24.39). This difference is statistically significant, <span class="math inline">\(p = .001\)</span> (that’s less than an alpha of .05), meaning the means are different enough that we might want to dig in a little bit deeper.</p>
<p>The next step, usually, would be to calculate Cohen’s <span class="math inline">\(d\)</span>, yet it is nowhere to be found in the output above. Other useful statistics are also missing, namely the mean difference. Although we can see the means for each group separately, why should you have to do the math when the point is for the software to do it for you? Lastly, this output doesn’t exactly make it easy to copy-and-paste into e.g., a table in Word, which one would usually want to do after conducting a statistical test. In other words, the output is not in a <a href="https://vita.had.co.nz/papers/tidy-data.pdf" target="_blank">tidy format</a>.</p>
</div>
<div id="my-solution" class="section level1">
<h1>My Solution</h1>
<p>I haven’t been able to find any existing functions that check these boxes, so I made my own wrapper function that shows output from <code>t.test()</code> and the <code>cohen.d()</code> function from the <code>psych</code> package in a tidy format. Here’s the same example as above using the function, which I have called <code>my.t</code>:</p>
<pre class="r"><code>my.t(mtcars, IV = am, DV = mpg)</code></pre>
<pre><code>## Loading required package: psych</code></pre>
<pre><code>## Warning: package &#39;psych&#39; was built under R version 3.6.2</code></pre>
<pre><code>## 
## Attaching package: &#39;psych&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:ggplot2&#39;:
## 
##     %+%, alpha</code></pre>
<pre><code>##     0.mean   1.mean     0.sd     1.sd mean.difference  std.err  conf.low
## 1 17.14737 24.39231 3.833966 6.166504       -7.244939 1.923202 -11.28019
##   conf.high         t       df     p.value cohens.d
## 1 -3.209684 -3.767123 18.33225 0.001373638     1.53</code></pre>
<table class="table" style>
<caption>
<span id="tab:table1">Table 1: </span>T-Test With <code>my.t</code> (IV = Transmission and DV = Miles Per Gallon)
</caption>
<thead>
<tr>
<th style="text-align:right;">
0.mean
</th>
<th style="text-align:right;">
1.mean
</th>
<th style="text-align:right;">
0.sd
</th>
<th style="text-align:right;">
1.sd
</th>
<th style="text-align:right;">
mean.difference
</th>
<th style="text-align:right;">
std.err
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
<th style="text-align:right;">
t
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:right;">
p.value
</th>
<th style="text-align:left;">
cohens.d
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
17.15
</td>
<td style="text-align:right;">
24.39
</td>
<td style="text-align:right;">
3.83
</td>
<td style="text-align:right;">
6.17
</td>
<td style="text-align:right;">
-7.24
</td>
<td style="text-align:right;">
1.92
</td>
<td style="text-align:right;">
-11.28
</td>
<td style="text-align:right;">
-3.21
</td>
<td style="text-align:right;">
-3.77
</td>
<td style="text-align:right;">
18.33
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:left;">
1.53
</td>
</tr>
</tbody>
</table>
<p>This output in Table <a href="#tab:table1">1</a> gives you all of the relevant statistics, clearly labeled, with Cohen’s <span class="math inline">\(d\)</span> included. The $d$ measure of effect size is quite large (1.53), which is about twice the size of the cutoff for a large effect size.</p>
<div id="formatting-option-and-an-illustration" class="section level2">
<h2>Formatting Option, and an Illustration</h2>
<p>Currently the output is in wide format, meaning that each statistic is its own column with the values for those statistics contained in the table row. If you prefer a different format, I have also added the <code>long =</code> argument that can optionally display output in long format, with each statistic indicated by the row with the value in a column:</p>
<pre class="r"><code>my.t(mtcars, IV = am, DV = mpg, long = TRUE)</code></pre>
<pre><code>##          Statistic  Value
## 1           0.mean  17.15
## 2           1.mean  24.39
## 3             0.sd   3.83
## 4             1.sd   6.17
## 5  mean.difference  -7.24
## 6          std.err   1.92
## 7         conf.low -11.28
## 8        conf.high  -3.21
## 9                t  -3.77
## 10              df  18.33
## 11         p.value   0.00
## 12        cohens.d   1.53</code></pre>
<table class="table" style>
<caption>
<span id="tab:table2">Table 2: </span>T-Test With <code>my.t</code> in Long Format (IV = Transmission and DV = Miles Per Gallon)
</caption>
<thead>
<tr>
<th style="text-align:left;">
Statistic
</th>
<th style="text-align:right;">
Value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
0.mean
</td>
<td style="text-align:right;">
17.15
</td>
</tr>
<tr>
<td style="text-align:left;">
1.mean
</td>
<td style="text-align:right;">
24.39
</td>
</tr>
<tr>
<td style="text-align:left;">
0.sd
</td>
<td style="text-align:right;">
3.83
</td>
</tr>
<tr>
<td style="text-align:left;">
1.sd
</td>
<td style="text-align:right;">
6.17
</td>
</tr>
<tr>
<td style="text-align:left;">
mean.difference
</td>
<td style="text-align:right;">
-7.24
</td>
</tr>
<tr>
<td style="text-align:left;">
std.err
</td>
<td style="text-align:right;">
1.92
</td>
</tr>
<tr>
<td style="text-align:left;">
conf.low
</td>
<td style="text-align:right;">
-11.28
</td>
</tr>
<tr>
<td style="text-align:left;">
conf.high
</td>
<td style="text-align:right;">
-3.21
</td>
</tr>
<tr>
<td style="text-align:left;">
t
</td>
<td style="text-align:right;">
-3.77
</td>
</tr>
<tr>
<td style="text-align:left;">
df
</td>
<td style="text-align:right;">
18.33
</td>
</tr>
<tr>
<td style="text-align:left;">
p.value
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;">
cohens.d
</td>
<td style="text-align:right;">
1.53
</td>
</tr>
</tbody>
</table>
<p>Say that in your car shopping, miles per gallon was one of just several criteria you were using to help you decide what kind of car to buy. In addition to miles per gallon, you also wanted to compare automatic vs manual transmissions in their level of <em>displacement</em>, which roughly describes “how fast a vehicle gets up and goes” (my <a href="https://matthewevanaman.netlify.app/img/dad.jpeg" target="_blank">dad</a> is a self-taught engineer who has built engines for 40 years, so I hope he will forgive me for this is description is less than accurate!). If you wanted to repeat what we did for vehicle displacement - measured in this dataset as displacement per cubic inch - you might repeat the above <span class="math inline">\(t\)</span>-test with displacement as your dependent variable instead of miles per gallon. Below is a table with the output of both tests side-by-side:</p>
<pre class="r"><code># conduct the tests
mpg.test &lt;- my.t(mtcars, IV = am, DV = mpg, long = TRUE)
disp.test &lt;- my.t(mtcars, IV = am, DV = disp, long = TRUE)
# relabel the columns with the name of the DV
mpg.test &lt;- mpg.test %&gt;% rename(MPG = Value)
disp.test &lt;- disp.test %&gt;% rename(&quot;Disp.&quot; = Value)
# combine into one dataframe
my.results &lt;- left_join(mpg.test, disp.test, by = &quot;Statistic&quot;)
# print the table
my.results</code></pre>
<table class="table" style>
<caption>
<span id="tab:table3">Table 3: </span>Comparing Group Differences in MPG and Displacement
</caption>
<thead>
<tr>
<th style="text-align:left;">
Statistic
</th>
<th style="text-align:right;">
MPG
</th>
<th style="text-align:right;">
Disp.
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
0.mean
</td>
<td style="text-align:right;">
17.15
</td>
<td style="text-align:right;">
290.38
</td>
</tr>
<tr>
<td style="text-align:left;">
1.mean
</td>
<td style="text-align:right;">
24.39
</td>
<td style="text-align:right;">
143.53
</td>
</tr>
<tr>
<td style="text-align:left;">
0.sd
</td>
<td style="text-align:right;">
3.83
</td>
<td style="text-align:right;">
110.17
</td>
</tr>
<tr>
<td style="text-align:left;">
1.sd
</td>
<td style="text-align:right;">
6.17
</td>
<td style="text-align:right;">
87.20
</td>
</tr>
<tr>
<td style="text-align:left;">
mean.difference
</td>
<td style="text-align:right;">
-7.24
</td>
<td style="text-align:right;">
146.85
</td>
</tr>
<tr>
<td style="text-align:left;">
std.err
</td>
<td style="text-align:right;">
1.92
</td>
<td style="text-align:right;">
34.98
</td>
</tr>
<tr>
<td style="text-align:left;">
conf.low
</td>
<td style="text-align:right;">
-11.28
</td>
<td style="text-align:right;">
75.33
</td>
</tr>
<tr>
<td style="text-align:left;">
conf.high
</td>
<td style="text-align:right;">
-3.21
</td>
<td style="text-align:right;">
218.37
</td>
</tr>
<tr>
<td style="text-align:left;">
t
</td>
<td style="text-align:right;">
-3.77
</td>
<td style="text-align:right;">
4.20
</td>
</tr>
<tr>
<td style="text-align:left;">
df
</td>
<td style="text-align:right;">
18.33
</td>
<td style="text-align:right;">
29.26
</td>
</tr>
<tr>
<td style="text-align:left;">
p.value
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;">
cohens.d
</td>
<td style="text-align:right;">
1.53
</td>
<td style="text-align:right;">
-1.49
</td>
</tr>
</tbody>
</table>
<p>Let’s take a stab at interpreting the results from this second <span class="math inline">\(t\)</span>-test with displacement as the dependent variable, shown in Table <a href="#tab:table3">3</a>. The mean difference is 146.85, meaning that automatic transmissions are associated with an extra 146.85 cubic inches of displacement on average. So while you might gain ~7 miles to the gallon by going with a manual transmission, you can also expect to lose 146.85 cubic inches of displacement.</p>
<p>OK, but what the heck does that mean? Is that an impressive number? It’s hard to tell for those who don’t spend time dealing with vehicle displacement. We might have been able to avoid this with miles per gallon, since miles per gallon is a familiar metric for those of us who drive and have to refill our gas tanks a few times a month. We readily understand how much money we would save if our vehicle got an extra 7 miles to the gallon. But I for one cannot readily understand how important a loss of 146.85 cubic inches of displacement is compared to a gain of 7 miles per gallon. If I were car shopping, I might like to know if this is an important difference, perhaps on the same scale as the difference in miles per gallon.</p>
<p>In Table <a href="#tab:table3">3</a>, we see the Cohen’s <span class="math inline">\(d\)</span> statistics for miles per gallon and displacement conveniently side-by-side. Both are very large effect sizes - quite a bit larger than <span class="math inline">\(0.8\)</span>, the rule of thumb for a “large” effect size given above. It’s nice to have these means differences expressed on a comparable scale (<span class="math inline">\(d\)</span>), because now we can, of course, compare them. Although the sign for displacement is negative (indicating that manual transmissions are associated with lower displacement than automatics), the absolute value is very close to that of miles per gallon. We can now say that however much gas we save by using a manual transmission instead of an automatic, we can expect to lose a proportionately similar amount of displacement per cubic inch. That is, the <em>magnitude</em> of the differences between between automatic and manual transmissions (effect sizes of 1.53 and -1.49, respectively) are pretty similar, even though the mean differences (7.24 miles per gallon and -146.85 cubic inches of displacement, respectively) are not comparable numbers.</p>
<p>Of course, this doesn’t <em>entirely</em> solve our problem: miles per gallon and displacement are too conceptually different to be compared meaningfully without added context. These tests would be most helpful if you also knew what adding 146.85 of displacement per cubic inch would feel like in terms of pushing your back against the seat as you accelerate in your new car. Maybe you would need twice as much displacement - 293.7, let’s say - in order for a gain in displacement to be noticeable. But in the absence of better information, it’s nice to know for the sake of car shopping that the <em>magnitude of the difference between the groups</em> is basically the same for miles per gallon and displacement. And now you have a function that gives you that information!</p>
</div>
</div>
<div id="full-function" class="section level1">
<h1>Full Function</h1>
<p>Copy-and-paste this function to use it in your own <code>R</code> projects. You will be prompted to install the <code>tidyverse</code> and <code>psych</code> packages if you do not already have them.</p>
<pre class="r"><code>my.t &lt;-
    function(data, IV, DV, long = FALSE, ...) {
      require(tidyverse)
      require(psych)
      IV.1 &lt;- enquo(IV)
      DV.1 &lt;- enquo(DV)
      means &lt;- suppressMessages(
        data %&gt;%
        group_by(!!IV.1) %&gt;%
        summarise(mean = mean(!!DV.1, na.rm = TRUE)) %&gt;%
          pivot_wider(names_from = !!IV.1, values_from =  &quot;mean&quot;)
        )
      names(means) &lt;- paste(names(means), &quot;mean&quot;, sep = &quot;.&quot;)
      SDs &lt;- suppressMessages(
        data %&gt;%
          group_by(!!IV.1) %&gt;%
          summarise(sd = sd(!!DV.1, na.rm = TRUE)) %&gt;%
          pivot_wider(names_from = !!IV.1, values_from =  &quot;sd&quot;)
      )
      names(SDs) &lt;- paste(names(SDs), &quot;sd&quot;, sep = &quot;.&quot;)

      IV.2 &lt;- rlang::sym(rlang::as_label(rlang::enquo(IV)))
      DV.2 &lt;- rlang::sym(rlang::as_label(rlang::enquo(DV)))
      form &lt;- expr(!! DV.2 ~ !! IV.2)
      t.tests &lt;- t.test(eval(form), data, var.equal = FALSE)
      stats &lt;- t.tests %&gt;% broom::glance(x)
      std.err &lt;- t.tests$stderr
      Ds &lt;-
        cohen.d(x = data %&gt;% select(!!DV.1, !!IV.1),
                group = deparse(substitute(IV)))$cohen.d %&gt;%
        as.data.frame %&gt;%
        select(effect) %&gt;%
        round(2) %&gt;%
        format(nsmall = 2)
      cols &lt;- c(&quot;conf.low&quot;, &quot;conf.high&quot;, &quot;statistic&quot;, &quot;parameter&quot;, &quot;p.value&quot;)
      means.table &lt;-
        cbind(means, SDs, stats[, &quot;estimate&quot;], std.err, stats[, cols], Ds)
      means.table &lt;- means.table %&gt;%
        rename(mean.difference = estimate, cohens.d = effect, t = statistic, df = parameter)
      rownames(means.table) &lt;- NULL
      if (long == TRUE) {
        means.table.long &lt;-
          means.table %&gt;% 
          t %&gt;% 
          data.frame(&quot;Value&quot; = .) %&gt;% 
          rownames_to_column(&quot;Statistic&quot;) %&gt;% 
          mutate(Value = as.numeric(as.character(Value))) %&gt;% 
          mutate(Value = round(Value, 2))
        return(means.table.long)
      } else{
        return(means.table)
      }
    }</code></pre>
</div>
<div id="references" class="section level1 unnumbered">
<h1>References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" line-spacing="2">
<div id="ref-coe2002effect" class="csl-entry">
Coe, R. (2002). <em>It’s the effect size, stupid: What effect size is and why it is important</em>. <a href="http://www.leeds.ac.uk/educol/documents/00002182.htm">Full Text</a>
</div>
<div id="ref-cohen2013statistical" class="csl-entry">
Cohen, J. (2013). <em>Statistical power analysis for the behavioral sciences</em>. Academic press. <a href="http://lab.rockefeller.edu/cohenje/PDFs/159CohenBigFishLittleFishTheSciences1989.pdf">Full Text</a>
</div>
</div>
</div>
